apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-node-app-autoscaling
  labels:
    app : my-node-app
spec:
  selector:
    matchLabels:
      project: app
  template:
    metadata:
      labels:
        project: app   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : node-app
          image: nazariatus/node:latest
          ports:
            - containerPort: 9007

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-node-app-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
     env  : prod
     owner: NazarPlaksa
spec:
  selector:
    project: app      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 9007  # Port on Load Balancer
      targetPort: 9007  # Port on Pod
  type: LoadBalancer